name: XcodegenSample
options:
  deploymentTarget:
    iOS: "14.0"
    macOS: "11.0"
# schemes:
#   'XcodegenSample (iOS)':
#     build:
#       targets:
#         'XcodegenSample (iOS)': all
#     test:
#       targets: ['Tests iOS']
#   'XcodegenSample (macOS)':
#     build:
#       targets:
#         'XcodegenSample (macOS)': all
#     test:
#       targets: ['Tests macOS']
targets:
  'XcodegenSample (iOS)':
    type: application
    platform: iOS
    sources: 
      - path: "iOS"
      - path: "Shared"
    settings:
      CODE_SIGN_STYLE: Automatic
      ORGANIZATIONNAME: "Daniel Ramteke"
      PRODUCT_BUNDLE_IDENTIFIER: no-org.XcodegenSample
      TARGETED_DEVICE_FAMILY: 1,2
      VERSIONING_SYSTEM: apple-generic
      SWIFT_VERSION: 5.4
      CURRENT_PROJECT_VERSION: 1
  'XcodegenSample (macOS)':
    type: application
    platform: macOS
    sources: 
      - path: "macOS"
      - path: "Shared"
    settings:
      CODE_SIGN_STYLE: Automatic
      ORGANIZATIONNAME: "Daniel Ramteke"
      PRODUCT_BUNDLE_IDENTIFIER: no-org.XcodegenSample
      TARGETED_DEVICE_FAMILY: 1,2
      VERSIONING_SYSTEM: apple-generic
      SWIFT_VERSION: 5.4
      CURRENT_PROJECT_VERSION: 1
  'Tests iOS':
    type: bundle.ui-testing   
    platform: iOS
    dependencies:
      - target: 'XcodegenSample (iOS)'
    sources: 
      - path: 'Tests iOS'
    info:
      path: Tests iOS/Info.plist
      properties:
        CFBundleVersion: '1'
        CFBundleShortVersionString: '1.0'
        CFBundleDevelopmentRegion: '$(DEVELOPMENT_LANGUAGE)'
        CFBundlePackageType: '$(PRODUCT_BUNDLE_PACKAGE_TYPE)'
        
  'Tests macOS':
    type: bundle.ui-testing   
    platform: macOS
    dependencies:
      - target: 'Tests macOS'
    sources: 
      - path: 'Tests macOS'
    info:
      path: 'Tests macOS/Info.plist'
      properties:
        CFBundleVersion: '1'
        CFBundleShortVersionString: '1.0'
        CFBundleDevelopmentRegion: '$(DEVELOPMENT_LANGUAGE)'
        CFBundlePackageType: '$(PRODUCT_BUNDLE_PACKAGE_TYPE)'
  